# Generated by Django 4.0.2 on 2022-02-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earToear', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jflaughs',
            name='number',
        ),
    ]
