# Generated by Django 4.0.2 on 2022-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earToear', '0002_remove_jflaughs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jflaughs',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jflaughs',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
